pluginManagement {
    resolutionStrategy {
        eachPlugin {
            var plugin = requested.id.toString()

            // ModGradle
            if (plugin.startsWith('org.moddingx.modgradle.')) {
                useModule "org.moddingx:ModGradle:${requested.version}"
            }
        }
    }
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            url = 'https://maven.minecraftforge.net/'
            content {
                includeGroupByRegex 'net\\.minecraftforge(\\..*)?'
                includeGroup 'de.oceanlabs.mcp'
                includeGroup 'net.minecraft'
                includeGroup 'cpw.mods'
            }
        }
        maven {
            url = 'https://maven.neoforged.net/releases/'
            content {
                includeGroupByRegex 'net\\.neoforged(\\..*)?'
            }
        }
        maven {
            url = 'https://repo.spongepowered.org/maven'
            content {
                includeGroupByRegex 'org\\.spongepowered(\\..*)?'
            }
        }
        maven {
            url = 'https://maven.parchmentmc.org'
            content {
                includeGroupByRegex 'org\\.parchmentmc(\\..*)?'
            }
        }
        maven {
            url = 'https://maven.moddingx.org'
            content {
                includeGroup 'org.moddingx'
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}
