version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1
  gradle: circleci/gradle@3.0.0

jobs:
  publish:
    machine:
      image: ubuntu-2204:2024.04.4
    resource_class: medium
    environment:
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - setup
      - run: |
          chmod +x ./gradlew
          ./gradlew publish

commands:
  setup:
    steps:
      - checkout
      - gradle/with_cache:
          cache_key: 'v1'
          steps:
            - run:
                name: chmod permissions
                command: chmod +x ./gradlew
            - run: ./gradlew build --parallel --console=plain
      - store_artifacts:
          path: ~/project/build/libs

workflows:
  start:
    jobs:
      - path-filtering/filter:
          name: filter
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/continue_config.yml
  publish:
    jobs:
      - publish:
          context:
            - maven
            - publishing
          filters:
            tags:
              only:
                - /.*/
            branches:
              ignore:
                - /.*/